//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentSlots.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentType
    {
        public int ApptTypeId { get; set; }
        public string ApptType { get; set; }
        public string ApptDescription { get; set; }
        public Nullable<int> ApptLength { get; set; }
    }
}
